### ISSUE TITLE
Add the option to consider a line preceding a display equation as a widow

### ISSUE THREAD

**Issue by tarsobcaldas** [gucci-on-fleek/lua-widow-control#16] opened 2022-02-18 14:30 UTC
Although technically not a widow, single lines before equations are ugly IMO. I was wondering if it is possible to detect this kind of line.

![equation widow](https://user-images.githubusercontent.com/40038251/154701168-adb020a2-c85e-4165-bdd9-d4d283c2cc76.png)

**Comment by gucci-on-fleek** [comment] 2022-02-18 23:48
Yeah, I agree, that looks bad.

Can you try changing
```tex
\usepackage{lua-widow-control}
```
to 
```tex
\usepackage{lua-widow-control}
\displaywidowpenalty=0
```

That might fix the problem. If it seems to work, let me know, and I'll make that the default in a future update.

**Comment by gucci-on-fleek** [comment] 2022-02-19 05:57
Sorry, that should be `\displaywidowpenalty=1`. I've edited the original reply.

**Comment by tarsobcaldas** [comment] 2022-04-04 14:29
I'm still having this problem, even setting \displaywidowpenalty=1.

**Comment by gucci-on-fleek** [comment] 2022-04-04 21:58
Alright, I'll look into it

**Comment by gucci-on-fleek** [comment] 2022-04-05 00:18
Hmm, I can't seem to reproduce this.

|With lua-widow-control|Without lua-widow-control|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/49086429/161653322-1de50f7f-a7ad-4a1f-83ea-19f33b993fb8.png)|![image](https://user-images.githubusercontent.com/49086429/161653334-1e8d9008-d5fa-466a-97db-1e00f9d7114d.png)|

```latex
\documentclass{article}

\usepackage[textwidth=345pt, textheight=550pt, showframe]{geometry}
\usepackage{amsmath}
\usepackage[debug=true]{lua-widow-control} % Comment this line out to disable

\def\sampletext{%
    Text text text text text text text text text text text text text text text
    text text text text text text text text text text text text text text text
    text text text text text text text text text text text text text text text
    text text text text text text text text text text text text text text.%
}

\begin{document}
    \vspace*{38\baselineskip}

    \sampletext

    \sampletext
    \begin{align}
        a &= b + c \\
        \alpha &= \beta + \gamma
    \end{align}
    \sampletext
\end{document}
```

---

My guess is that the previous page in your document doesn't have any "good" paragraphs to stretch, so lua-widow-control just gives up. If that's the case, your log file probably has lines like
```log
Module lua-widow-control Info: Widow/orphan detected. Attempting to remove. on input line XX
Module lua-widow-control Warning: Widow/Orphan NOT removed on page NN on input line XX
```
which usually means that you'll have to rewrite something on that page. 

If that's not the case, then try compiling your document with the debug mode enabled:
```latex
\usepackage[debug=true]{lua-widow-control}
```
and reply with the log file and I'll try and see if something weird is happening.

**Comment by gucci-on-fleek** [comment] 2022-05-19 07:31
I'm closing this for now since I'm not able to reproduce this; but please, feel free to comment/reopen if this is still an issue.

**Closed by gucci-on-fleek** 2022-05-19 07:31 UTC
Labels: Minor Bug, Generic/All Formats
